[package]
name = "rt_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clippy = "0.0.302"
indicatif = "0.18.0"
rand = "0.9.2"

[build]
rustflags = ["-C", "target-cpu=native", "-C", "force-frame-pointers=yes"]

[profile.release]
debug = true
codegen-units = 1
lto = "fat"
